#loc = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":56:0)
module {
  tt.func public @no_cast(%arg0: !tt.ptr<i32> loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":56:0), %arg1: !tt.ptr<i32> loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":56:0)) attributes {noinline = false} {
    %c5_i32 = arith.constant 5 : i32 loc(#loc1)
    %c4_i32 = arith.constant 4 : i32 loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %0 = tt.load %arg0 : !tt.ptr<i32> loc(#loc2)
    %1 = tt.addptr %arg0, %0 : !tt.ptr<i32>, i32 loc(#loc3)
    %2 = tt.load %1 : !tt.ptr<i32> loc(#loc4)
    %3 = arith.muli %2, %c2_i32 : i32 loc(#loc5)
    %4 = tt.addptr %1, %3 : !tt.ptr<i32>, i32 loc(#loc6)
    %5 = tt.load %4 : !tt.ptr<i32> loc(#loc7)
    %6 = arith.muli %5, %c4_i32 : i32 loc(#loc8)
    %7 = tt.addptr %4, %6 : !tt.ptr<i32>, i32 loc(#loc9)
    %8 = tt.load %7 : !tt.ptr<i32> loc(#loc10)
    %9 = arith.muli %8, %c5_i32 : i32 loc(#loc11)
    %10 = tt.addptr %7, %9 : !tt.ptr<i32>, i32 loc(#loc12)
    %11 = tt.load %10 : !tt.ptr<i32> loc(#loc13)
    tt.store %arg1, %11 : !tt.ptr<i32> loc(#loc14)
    tt.return loc(#loc15)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":58:29)
#loc3 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":58:21)
#loc4 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":64:23)
#loc5 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":64:15)
#loc6 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":64:11)
#loc7 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":66:30)
#loc8 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":66:22)
#loc9 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":66:18)
#loc10 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":68:32)
#loc11 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":68:24)
#loc12 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":68:20)
#loc13 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":69:16)
#loc14 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":70:23)
#loc15 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":70:4)