#loc = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":56:0)
module {
  tt.func public @cast(%arg0: !tt.ptr<i32> loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":56:0), %arg1: !tt.ptr<i32> loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":56:0)) attributes {noinline = false} {
    %c4_i32 = arith.constant 4 : i32 loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %c1_i32 = arith.constant 1 : i32 loc(#loc2)
    %0 = tt.addptr %arg0, %c1_i32 : !tt.ptr<i32>, i32 loc(#loc2)
    %1 = tt.bitcast %0 : !tt.ptr<i32> -> !tt.ptr<i64> loc(#loc3)
    %2 = tt.addptr %1, %c2_i32 : !tt.ptr<i64>, i32 loc(#loc4)
    %3 = tt.bitcast %2 : !tt.ptr<i64> -> !tt.ptr<i16> loc(#loc5)
    %4 = tt.addptr %3, %c4_i32 : !tt.ptr<i16>, i32 loc(#loc6)
    %5 = tt.bitcast %4 : !tt.ptr<i16> -> !tt.ptr<i32> loc(#loc7)
    %6 = tt.load %5 : !tt.ptr<i32> loc(#loc8)
    tt.store %arg1, %6 : !tt.ptr<i32> loc(#loc9)
    tt.return loc(#loc10)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":58:21)
#loc3 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":58:27)
#loc4 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":64:11)
#loc5 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":66:19)
#loc6 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":66:48)
#loc7 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":68:21)
#loc8 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":69:16)
#loc9 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":70:23)
#loc10 = loc("/home/nhat/triton-scratchpad/ptrs/bitcast.py":70:4)
